version: "3"

services:
  project3:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./project3:/project3
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"